### ISSUE TITLE
I can't see videos 

### ISSUE THREAD

**Issue by Pkfier** [igdmapps/igdm#1004]
My sister sent me a video but I can't watch it

**Comment by Cadill** [comment]
I noticed that when I send videos, they don't play and appear as still images.  Is this expected?

**Comment by baptx** [comment]
It is a bug. If someone wants to view videos on a desktop web browser without using the proprietary mobile app, here is a script I made to backup Instagram messages history, which includes the URL to image, video and audio files: https://gist.github.com/baptx/1e61eef2e1ec200b6e7b32409f79c07f
