### ISSUE TITLE
When sending a picture in a group chat, it makes a new chat

### ISSUE THREAD

**Issue by mohamed-ahmed** [igdmapps/igdm#1056]
**Describe the bug**
When sending a picture in a group chat, it creates a new group chat with all the same members and sends the photos there

**To Reproduce**
1. Go to a group chat
2. Click send photo button
3. Send a photo
4. New group chat is created with same members and photo is sent there.

**Expected behavior**
Expect photo to be sent in that group chat

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version Mojave

**App version :**
 - Version 2.7.0

**Comment by gotem3239** [comment]
No, it's not the same as those. 
I'm experiencing this issue too now. Everytime I send an image in a group chat it makes a whole new group. Any idea what i can do to fix this?? It's very annoying :(
