### ISSUE TITLE
Unable to save pictures?

### ISSUE THREAD

**Issue by Xenuty** [igdmapps/igdm#1086]
It's written on the download page that we should be in able to download images sent to us by our friends in DMs, but while I can download audio messages and video clips (from profiles, not direct), I can't download images. From anywhere. Is there any way to fix this? 
And if it's on purpose, is there a way to add this feature? I'd like to be in able to save my DMs. >.<

**Comment by Hattshire** [comment]
I only see "add ability to copy image URL to clipboard" on the releases page, and this feature it's working for me.
You can copy the url, then paste it on a browser or download manager and download it from there.

Did you meant to make a feature request?

**Comment by Xenuty** [comment]
> I only see "add ability to copy image URL to clipboard" on the releases page, and this feature it's working for me.
> You can copy the url, then paste it on a browser or download manager and download it from there.
> 
> Did you meant to make a feature request?

Thank you, I did not know about this. 
I wish they added a more simplefied version, but this works I guess, thank you for your reply.
(video support should also be added)

**Comment by KAMiKAZOW** [comment]
Supe of #997
