### ISSUE TITLE
Won't let me login.

### ISSUE THREAD

**Issue by Originallytanaa** [igdmapps/igdm#1089]
When i try to login onto my Instagram it doesn't work. It always have an different excuse onto why it doesn't want to work.

**Comment by someone857** [comment]
Excuse like? Please provide information, this is not useful for any troubleshooting

**Comment by bluegod** [comment]
I don't think this app is working anymore. After entering the username/password, it asks for a security code sent to my email. After entering it, it just keeps asking for the security code again and again. I do receive an email every time with a new security code, but it just stays in a loop.
