### ISSUE TITLE
Spaces in sentences don't render

### ISSUE THREAD

**Issue by mendess** [igdmapps/igdm#1093]
**Describe the bug**
No spaces are rendered anywhere in the program. Numbers also appear spaced out.

**To Reproduce**
I'm on Arch Linux, and installed through the [AUR](https://aur.archlinux.org/packages/igdm/), which uses this [link](https://github.com/ifedapoolarewaju/igdm/releases/download/v2.7.1/IGdm-2.7.1.zip) to download the app.

**Expected behavior**
Spaces in words, numbers should use the same font as other letters

**Screenshots**
![image](https://user-images.githubusercontent.com/19352680/65832270-571f3180-e2b9-11e9-9b87-136464d20f76.png)
That messages should look like this
> Ta tudo a correr bem

**Desktop (please complete the following information):**
```
uname -a
Linux weatherlight 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
```

**App version (please complete the following information):**
v2.7.1

**Additional context**
I have a minimal install of arch, maybe I'm missing some fonts, what fonts are used in the program?

**Comment by ifedapoolarewaju** [comment]
thank you for reporting
