### ISSUE TITLE
IGDM SAYS I HAVE TWO-FACTOR AUTHENTICATION

### ISSUE THREAD

**Issue by francisnyalali** [igdmapps/igdm#1097]
Hey, I tried downloading IGDM on my PC the other day but it says I have two factor authentication, but come to check I switched it off. What could be the problem???

**Comment by ifedapoolarewaju** [comment]
> but come to check I switched it off

this could be some cache problem. However [2FA is now supported](https://github.com/igdmapps/igdm/releases/tag/v2.8.0), so this should no longer be an issue
