### ISSUE TITLE
My email adress didn't recieve vertification code

### ISSUE THREAD

**Issue by ShapeShifted** [igdmapps/igdm#1103]
My email adress is qing530@hotmail.com and when I try to login IGDM with my correct email and password, IGDM tells me to enter vertification code. However, I didn't recieve the code. I can't login into IGDM because of this.

**Comment by juanc0r** [comment]
i have the same problem, if any know how to fik that please comunicate, the bot dont have any chat whit information to fix this.

**Comment by ShapeShifted** [comment]
Hello? Is there any reply?

**Comment by ifedapoolarewaju** [comment]
the code might have been sent to your phone instead. The new version (2.8.0) no has a message telling you to check your mail or sms
