### ISSUE TITLE
Doesn't upload JPG files to Direct (MacOS)

### ISSUE THREAD

**Issue by nick7ikin** [igdmapps/igdm#1113]
When attempting to send JPG-image via Direct it shows popup: "Image upload failed. :( Please ensure your image is in .jpg format.".

I'm sure that my images are in jpg-format)). I took images from internet and made them myself converting png to jpg.

Recently it worked properly, but now it is broken

**Comment by billcapell** [comment]
I have the exact same problem with files that I successfully uploaded a few weeks ago !!

**Comment by ifedapoolarewaju** [comment]
this issue seems to have been from instagram side, and it works again now.
