### ISSUE TITLE
Issue with 2-factor authentication (sms or app generated code)

### ISSUE THREAD

**Issue by fedecupe** [igdmapps/igdm#1115]
Hi, I've got issues with 2 factor auth.
After inputting user and password, I correctly receive an SMS with the 6-digit code, if I input that after few seconds the code request appears again (but no new message is sent from ig).

- If I insert the message code again, I get an error about the code being incorrect (Please check the security code and try again.)
- If I insert a code from the authenticator app I get a weird message (Instagram call checkpoint for this action!)

Anyhow, I can't login :(
Happy to help debugging if you need.

**Comment by fresheed** [comment]
Have you managed to solve it? I can't login too. After I type the 6-digit code, I just receive another one, and so on.
