### ISSUE TITLE
Can't Send DM on Instagram

### ISSUE THREAD

**Issue by PravinEluminous** [igdmapps/igdm#1128]
Hello,

We are using IGdm for DM for our instagram. It is blocking the action to send DM. Kindly guide us on the issue.

I have attached the image as well.

![image](https://user-images.githubusercontent.com/57666014/68667200-69081b80-056b-11ea-94cb-d1bd24802825.png)

**Comment by baptx** [comment]
Are you using a VPN or proxy? I have the same problem since several weeks, it happens when you try to contact someone new only. I heard Instagram has changed how they detect spam recently: https://github.com/igdmapps/igdm/issues/1133
