### ISSUE TITLE
The typing area stucks big

### ISSUE THREAD

**Issue by Elatarisi** [igdmapps/igdm#1129]
When I write big paragraphs the typing area gets bigger (as usual) but after I send the message it stucks big for no reason. That gives me less area to read the messages for no reason.

**Comment by someone857** [comment]
I noticed that in the past, but the text area resizes back as soon as you start typing, no? Can you confirm if that is enough or if you still need this fixed?

**Comment by Elatarisi** [comment]
Oh I missed that, I should type something to get back. Thanks, it's ok, I can deal with it.
