### ISSUE TITLE
I couldn't to login cause circle message requests..

### ISSUE THREAD

**Issue by emlen** [igdmapps/igdm#1138]
**Steps to reproduce the behavior:**
1. Go to login page
2. Input my Instagram login and password, pushing the button
3. Input code from security sms-message
4. Got new and new Security -code request window without stop when enough..

**Desktop:**
 - OS: ArchLinux 5.3.1 #1 SMP PREEMPT Mon Sep 30 20:27:23 MSK 2019 i686 GNU/Linux

**App version:**
 - Version aur/igdm-bin 2.8.1-1 (+0 0.00%)

**Comment by eerburu** [comment]
I have the same problem. It looks like a loop. I inserted like 3 times the code.
I quit the program. Enter credential. IG sent me the same verification code (not sure why, maybe random, maybe the last code didn't expire yet and they sent the same), I enter the code, it worked.

**Comment by emlen** [comment]
> I have the same problem. It looks like a loop. I inserted like 3 times the code.
> I quit the program. Enter credential. IG sent me the same verification code (not sure why, maybe random, maybe the last code didn't expire yet and they sent the same), I enter the code, it worked.

 it did not work in my case

**Comment by emlen** [comment]
![err](https://user-images.githubusercontent.com/12050586/69608096-b1c5d700-1037-11ea-87c1-6f43c4625f59.png)

**Comment by eerburu** [comment]
Did you put the code with a space between the two numbers (123 456) instead of (123456)? You have to do it like the second way (123456).
Try quitting igdm with Cmd (⌘) + Q to quit and then start it again.

**Comment by emlen** [comment]
> Did you put the code with a space between the two numbers (123 456) instead of (123456)? You have to do it like the second way (123456).
Error was when I tried to use constant secure codes with 8 digits
> Try quitting igdm with Cmd (⌘) + Q to quit and then start it again.
I tried, honestly)

**Comment by eerburu** [comment]
Maybe the program has a problem  with the 8 digits code. Is there a way to use a 6 digits code? Not sure what authentication system are you using.
