### ISSUE TITLE
verification code

### ISSUE THREAD

**Issue by AnonymousKali** [igdmapps/igdm#1147]
doesnt send a verification code so i cant even use the app :/

**Comment by EpicGamesOfficial** [comment]
IGdm has login support for accounts with **two-factor authentication** enabled.

**Comment by Bengel2004** [comment]
It doesn't work for me either honestly, 2FA doesn't work

**Comment by Jay991** [comment]
same here https://github.com/igdmapps/igdm/issues/1158
