### ISSUE TITLE
Sending pics to persons

### ISSUE THREAD

**Issue by sandrahaircut** [igdmapps/igdm#1149]
i have a problem od sending pics to other people it shows an error it say to be sure if it is JPG and it was a JPG file but does not work

**Comment by BRUH31** [comment]
same

**Comment by JAILeXY** [comment]
i have an issue just sending videos like this sht is slick aggy

**Comment by sandrahaircut** [comment]
i even re- instal ig:dm but still not can send pics

**Comment by BRUH31** [comment]
Tried that didn't work

**Comment by TallGuysFreeADMIN** [comment]
same issue.

**Comment by SunniJB** [comment]
Same issue

**Comment by cageyv** [comment]
Same issue. No problems a month ago. 
Also reproduce on paid version or old version.
Probably edits on the Instagram side

**Comment by coldnrainy** [comment]
Problem  persists. I noticed that when I tried to upload a JPG I had converted from PNG I got a failed error message. When I tried to upload an image that was natively JPG it said "being uploaded" but never uploaded.

**Comment by teckyca** [comment]
same

**Comment by arslion** [comment]
same problem

**Comment by coldnrainy** [comment]
For those still looking for a solution to the photo upload issue, Instagram has opened up DMs on the web to everyone. Just go to www.instagram.com and you can access your DMs. Image upload works flawlessly. I prefer this app but until the image upload issue is fixed, this is a workaround.
