### ISSUE TITLE
why i couldn't log into IGDM?

### ISSUE THREAD

**Issue by Bestvibe** [igdmapps/igdm#1154]
I use my instagram account log into this ,but failed, why?
![image](https://user-images.githubusercontent.com/58585534/70304693-7ac4a200-183d-11ea-87a6-9d2742a5278e.png)

**Comment by someone857** [comment]
Can you login to instagram.com from the same computer/network?

**Comment by Bestvibe** [comment]
hello ,what does it mean and why login into instagram?






------------------

&nbsp; &nbsp; &nbsp; http://www.bestvibe.com

&nbsp; &nbsp; &nbsp; service@bestvibe.com

&nbsp; &nbsp; &nbsp;&nbsp;http://www.shareasale.com/join/89827&nbsp;&nbsp;

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
