### ISSUE TITLE
upload jpeg error

### ISSUE THREAD

**Issue by MaxTsikal** [igdmapps/igdm#1156]
i can't upload jpeg/jpg format of picture

**Comment by someone857** [comment]
How is that different from #1149 , #1150 and #1155 ?

**Comment by MaxTsikal** [comment]
The same problem

**Comment by someone857** [comment]
So please avoid posting duplicate issues. It was already on the template that you probably removed when posting:

**Please ensure that the issue you are about to report has not previously been reported by anyone else. You can [search existing issues here](https://github.com/ifedapoolarewaju/igdm/issues) **
