### ISSUE TITLE
Sending images

### ISSUE THREAD

**Issue by ferg13** [igdmapps/igdm#1173]
I don't know why can't send images in jpg. Can fix the problem? Thank you!

**Comment by MfgGres** [comment]
<img width="396" alt="Screen Shot 2019-12-29 at 19 23 28" src="https://user-images.githubusercontent.com/31015158/71563576-a4559f80-2a70-11ea-8dba-a253bb9e8c23.png">

**Comment by Daviture** [comment]
Same problem here
