### ISSUE TITLE
Be able to enter developer mode

### ISSUE THREAD

**Issue by katbasie** [igdmapps/igdm#1181]
I think there are HTML files missing in the GIT to run the app. Is it possible to enable developer mode in the exe so extra apps/support can be created for the application?

**Comment by HaraseesG** [comment]
What would you want to be able to do in this developer mode?

**Comment by ANA-Y-N** [comment]
i do not think about it

**Comment by katbasie** [comment]
I am a university student at USC and wanted to access GUI elements for a
project I'm doing in class.

On Tue, Feb 11, 2020 at 9:54 AM ANA <notifications@github.com> wrote:

> i do not think about it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_igdmapps_igdm_issues_1181-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAN4UCFBMSRJK2J2XAIH75WTRCLQ65A5CNFSM4KDQOLN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELNNNOQ-23issuecomment-2D584767162&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eA_1VoOA-bSQjXi0La_vCg&m=up8JU_-W1HpkOlblKxat5SYEbDlKRibkneBQuqoDgnI&s=3VyXS2NrO9AFa3N5z7tz3LYiRTgpWT91svQLNSKhMaA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN4UCFHEOYBYFODKKM4M7LTRCLQ65ANCNFSM4KDQOLNQ&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eA_1VoOA-bSQjXi0La_vCg&m=up8JU_-W1HpkOlblKxat5SYEbDlKRibkneBQuqoDgnI&s=ey4ABl7nQohy2c3ngW5-E5l19E2H7OHGQ9_g1PHeHcs&e=>
> .
>


-- 
-Katherine Pacioni

**Comment by ANA-Y-N** [comment]
Can you give me more information on the subject?

**Comment by katbasie** [comment]
I wanted to make an extension that would allow messages to be scheduled to
sent. It is a similar consent to Boomerang which is a Gmail extension that
allows emails to be scheduled to sent at a specified time rather than
immediately.

On Tue, Feb 11, 2020 at 2:24 PM ANA <notifications@github.com> wrote:

> Can you give me more information on the subject?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_igdmapps_igdm_issues_1181-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAN4UCFGC4SATIOJ572ALXPDRCMQRVA5CNFSM4KDQOLN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELOKPRQ-23issuecomment-2D584886214&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eA_1VoOA-bSQjXi0La_vCg&m=pfbbkgMIvPj6_cQeOmnlAUIB3lkEBNkBkfzazYUNpaY&s=kTdKRS8lWDTr8h8rJkxBxAkZK5h9HLJW7kVwGmz-aXw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN4UCFDI6LV5OXD3PTD4I6TRCMQRVANCNFSM4KDQOLNQ&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eA_1VoOA-bSQjXi0La_vCg&m=pfbbkgMIvPj6_cQeOmnlAUIB3lkEBNkBkfzazYUNpaY&s=yScMcmwxOhEqlbxM5KW9SrrDFDd9X7aiapQcnL93uSs&e=>
> .
>


-- 
-Katherine Pacioni

**Comment by someone857** [comment]
if you download the source code and start the app with electron code, it will have access to dev tools. just not on the released version.
this should be #closed
