### ISSUE TITLE
File index.html & login.html not found

### ISSUE THREAD

**Issue by newarifrh** [igdmapps/igdm#1195]
Hello, thank you for developing the IGdm application. IGdm is very useful when I have to connect with friends but my cellphone is running out of battery 🥰

I am very interested in contributing to this application, specifically modifying certain features. But I am having problems because the index.html & login.html documents are not in this repository.

Look at the .gitignore document: https://github.com/igdmapps/igdm/blob/master/.gitignore

Can you include the file in this repository?
Thanks 😊

**Comment by ifedapoolarewaju** [comment]
does files are in gitignore because when you run the app locally in dev mode they are auto-generated. The are auto-generated from these [.pug files](https://github.com/igdmapps/igdm/tree/master/browser/views). To have them generated locally, just run `npm start`
