### ISSUE TITLE
Uploading photos in chats

### ISSUE THREAD

**Issue by abhishekraj0507** [igdmapps/igdm#1208]
i am not able to upload photos in chats. It shows upload fail all the time. please fix it.

**Comment by ANA-Y-N** [comment]
you can not upload photos in your instagram  on your lap top?

**Comment by fabrikanec** [comment]
Same problem, still not working.
![2020-02-18-134957_1920x1080_scrot](https://user-images.githubusercontent.com/15125109/74730584-706c4e80-5257-11ea-861b-d73f3d99fe20.png)
