### ISSUE TITLE
File Permission issues with saving session file

### ISSUE THREAD

**Issue by immigrationist** [igdmapps/igdm#1209]
So I downloaded and connected it with my instagram account on my laptop. The problem here is it keeps giving errors on the app. What should I do?

**Comment by HaraseesG** [comment]
What errors are you getting?

**Comment by ANA-Y-N** [comment]
What do you mean by keeping program errors?

**Comment by Nereg** [comment]
https://prnt.sc/r1t3mz here it is. Windows 10

**Comment by Nereg** [comment]
Any fix?

**Comment by ANA-Y-N** [comment]
what is your browser?

**Comment by ANA-Y-N** [comment]
Are you sure your password?I have a suggestion for you: go to Google Chrome Marketplace and find and add instagram to your browser. That way, the app can be easily saved there and you can easily log in.

**Comment by Nereg** [comment]
> what is your browser?
It's desktop app :/
