### ISSUE TITLE
Problem with playing videos when the post is a carousel.

### ISSUE THREAD

**Issue by franbergomas** [igdmapps/igdm#1210]
### How to reproduce the error:
**1.** Go to a DM's.
**2.** Open a video that was sent to you
**3.** If the publication has more than one video or image, the video won't play.

### Example: The first one is an image with a joke, and the next one is the actual video.
![image](https://user-images.githubusercontent.com/60909717/74210095-2dafe280-4c69-11ea-80a7-093759676e0b.png)
![image](https://user-images.githubusercontent.com/60909717/74210101-33a5c380-4c69-11ea-943f-c71eb74b2d76.png)

-OS: KDE Neon
-Version: User Edition 5.17 x86_64

App Version: v2.8.0

**Comment by vineetvk01** [comment]
Hey! I am working on this issue.

**Comment by yorga06** [comment]
videos open as images, how do i fix them?

**Comment by vineetvk01** [comment]
Hey @yorga06, can you tell me more details:
1. Where you faced this issue? Which branch you are using for development?
2. This happened while playing a video in the carousel or a general video in the Direct Message ?

**Comment by yorga06** [comment]
1. I got this issue about a week ago! I use the executable from https://igdm.me/
2. I think is in DM not carousel, the window open and show a picture and if i drag it in a browser has JPG extension

**Comment by yorga06** [comment]
> Hey @yorga06, can you tell me more details:
> 
> 1. Where you faced this issue? Which branch you are using for development?
> 2. This happened while playing a video in the carousel or a general video in the Direct Message ?

I got this issue about a week ago! I use the executable from https://igdm.me/
I think is in DM not carousel, the window open and show a picture and if i drag it in a browser has JPG extension
