### ISSUE TITLE
IGDM

### ISSUE THREAD

**Issue by satya5039** [igdmapps/igdm#1214]
I can't login into my instagram account since evening and i don't know why!Please help me with this asap

**Comment by ANA-Y-N** [comment]
How many accounts do you have on Instagram?

**Comment by satya5039** [comment]
It's all fine now.I could login after few attempts i don't what was wrong
my internet or something but it's ok now.
thanks for taking and responding to the issue!

**Comment by ANA-Y-N** [comment]
you're welcome
