### ISSUE TITLE
Can't send photo to direct

### ISSUE THREAD

**Issue by fabrikanec** [igdmapps/igdm#1216]
On linux i can't send photo in direct. All types: jpg, png, jpeg. 

![2020-02-18-134957_1920x1080_scrot](https://user-images.githubusercontent.com/15125109/75031780-13bb9e80-54b8-11ea-9f1d-2ac980bd16f5.png)

**Comment by ANA-Y-N** [comment]
Right-click on the box next to the sticker image, then select the image you want from your files and then send
