### ISSUE TITLE
Verification code does not work

### ISSUE THREAD

**Issue by mbartkow** [igdmapps/igdm#1218]
While trying to log in to my account I get a request to type the verification code. I get the code on my phone (6 digits), I retype it into the window, and it closes. Instead of letting me in, there is another window popping up and asking for the ver code again. I get a different code each time, but the loop does not end. 
I'm on Mac osx 10.9.5

**Comment by Madac1** [comment]
same here, I'm using linux mint 19.3 tricia with kernel 5.5 generic. Installed IGdm from the .deb files through dpkg and opens correctly.

**Comment by Madac1** [comment]
Tried disabling and re-enabling the 2fa and trying logging in IG in a incognito window on the browser.
IG sends you a sms when it algorithm detects your account has a new login attempt in a new location or IP or app for login (like trying to login in chrome and later in firefox browsers), when you login with that code in that specific location, ig stores that and later it doesn't require that you verify that "location", but seems that IGdm doesn't recognize correctly that code or doesn't send it correctly to the ig servers and fails in that verification process, although you had 2fa disabled.
