### ISSUE TITLE
Infinite code verification

### ISSUE THREAD

**Issue by bphd** [igdmapps/igdm#1219]
All in the title folks !

**Comment by Dea1993** [comment]
same problem.
i've also tried to disable 2fa, but login not works

**Comment by aryehbeitz** [comment]
i get a code by sms and it has a space. without a space, it sends another sms. with space, it pops up an error

**Comment by ANA-Y-N** [comment]
Did you enable 2-step verification on your account?

**Comment by bphd** [comment]
Closing an issue, the best way from far to enhance the software 👏👏👏👏👏👏👏

**Comment by ifedapoolarewaju** [comment]
@bphd the issue has been fixed in the lates release v3.0.0.

There are too many duplicates of the same issue (this issue for example is a duplicate with many other similar versions), so it's tough commenting on all of them before closing them.

**Comment by bphd** [comment]
Mark as duplicate of the older one and type a resolve in it, so the users will see what you've done

**Comment by ifedapoolarewaju** [comment]
> type a resolve

is effectively "commenting", which is the tough part when there are too many of them. Lots of them are marked as duplicate, but I didn't catch all.

Ideally, it would help if duplicate issues are not created to start with. There are messages that hint users to see if a similar issue already exist before creating new ones.

**Comment by bphd** [comment]
No, read me

On the OLDEST issue opened about that (only one) you write the resolution, you make a report about that

And THEN, you mark all the others as duplicate of the oldest one, you get me?
