### ISSUE TITLE
I can't send any photos.

### ISSUE THREAD

**Issue by teckyca** [igdmapps/igdm#1221]
When I try to send a picture it says "image upload failed. please ensure your picture is in .jpg" when it already is. I don't know what to do and it keeps saying that. Please fix it as fast as possible. Thank you !
![Untitled](https://user-images.githubusercontent.com/61429760/75180972-89846c00-573d-11ea-9515-fab31d83342f.png)

**Comment by aditisstillalive** [comment]
I'm having this issue too, I'm trying to upload picture saved from Windows' snipping tool, it is in .jpg format, but I got the same message.

**Comment by teckyca** [comment]
How do I undo that?

пет, 1. мај 2020. у 08:43 Ifedapo .A. Olarewaju <notifications@github.com>
је написао/ла:

**Comment by ifedapoolarewaju** [comment]
Hi there,

Please update your app to the latest version. Image uploads should work
fine now.
