### ISSUE TITLE
Allow users to save images directly without having to copy the image URL

### ISSUE THREAD

**Issue by ifedapoolarewaju** [igdmapps/igdm#1225]
As of now, the only way you can save images is by copying the image URL and loading it via browser. It'll be nice to have a way to save it directly via the app.

**Comment by vineetvk01** [comment]
I am taking up this minor enhancement.

Steps for saving any image: 
1. Right click on the image.
2. "**Save Image As**" menu will be added below the 'Copy URL to clipboard'.
3. showSaveDialog will defile path to save.
4. Image will be Downloaded.

**Comment by ANA-Y-N** [comment]
Thank you for your solution
