### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by ajsb85** [igdmapps/igdm#1230]
git clone
npm install
npm start

error in the devtools:

`Not allowed to load local resource: file:///Users/ajsb85/igdm/browser/login.html`

![image](https://user-images.githubusercontent.com/663460/75674020-8846c800-5c84-11ea-90da-19aecb741c4e.png)

**Comment by samarthdave** [comment]
Hi! I just fixed this error. I'll reference #1176 just in case.

**see if this helps:**
```
sudo npm install --global gulp-cli # you'll need to install gulp
# then run gulp build
gulp build
# and then try again
npm start
```
