### ISSUE TITLE
unified eslint

### ISSUE THREAD

**Issue by ifedapoolarewaju** [igdmapps/igdm#1236]
At the moment the entire project has quite some inconsistencies. For example, some variables use the `var` keyword, while some others use `let` and `const`. Some parts of the code add semi colons to each line, while others don't. It'd be nice if we run a linter that helps us maintain the same style of code. We can do this by adding an `.eslintrc` and also add npm scripts to help run the linting.

**Comment by vineetvk01** [comment]
Yes, we should consider this setup to have a consistent coding-style. I am taking this up first before other fixes. :D 
Lets do this :+1:

**Comment by vineetvk01** [comment]
Hey, @ifedapoolarewaju. Please close this issue :)
