### ISSUE TITLE
"Image Upload Failed"

### ISSUE THREAD

**Issue by Marcos-Molina** [igdmapps/igdm#1244]
The program doesn't let me send JPEG/JPG files. I tried many different ones, it always rejects. A warning appears saying "Image Upload Failed. Please ensure your image is in .jpg format". This is weird as the program did let me send pictures before.

**Comment by coldnrainy** [comment]
This has been a long-standing issue. Just wanted to let you and other know that Instagram has opened up DMs on their website now for everyone. It works flawlessly. I prefer the app but you can upload images with ease now.
