### ISSUE TITLE
Can't login - repeatedly asking for confirmation code

### ISSUE THREAD

**Issue by eVen-gits** [igdmapps/igdm#1245]
**Describe the bug**
After filling the user name and password, I am sent the code via SMS. After entering the code into the app, I am not logged in, but instead, asked for the code again.

**To Reproduce**
1. Start the application
2. Fill uname and passwd
3. Press login
4. Wait for confirmation code (email/SMS)
5. Fill confirmation code into the newly opened confirmation window

**Expected behavior**
User should be logged in.

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu 19.10

**App version (please complete the following information):**
 - 2.8.1-x86_64

**Additional context**
I've tried using " " (space) in between two numbers that are sent, but it doesn't change the outcome.

Occasionally, I will also get this error:
![image](https://user-images.githubusercontent.com/2612606/76199309-ec6f0c00-61ef-11ea-8b2c-9f4be88756c8.png)

**Comment by danieldfc** [comment]
Really, the bug is happening all of a sudden. So when I try to connect with the received code, it asks again, or if I put the code wrong it shows the mentioned error.
