### ISSUE TITLE
Show loading GIF when fetching "Unfollowers"

### ISSUE THREAD

**Issue by ifedapoolarewaju** [igdmapps/igdm#1256]
Right now, when fetching the user's unfollowers, the screen just waits and does nothing until the list is loaded, and then it is displayed. It'd be nice to instead show the user that the list is being loaded with the loading GIF

**Comment by vineetvk01** [comment]
Even, (close) not working. 

![cross-not-working](https://user-images.githubusercontent.com/15632559/77207811-5789de00-6b20-11ea-95d4-3e3f40f8b4e7.gif)
--
Working on this.
