### ISSUE TITLE
 Infinite loop receiving access code in email

### ISSUE THREAD

**Issue by danieldfc** [igdmapps/igdm#1257]
**Describe the bug**

So when we try to log into the application, we receive a security code by email. When we put the code in, it tries to verify and then sends the code again in the email. I tried to log in more than 3 times and I get the same problem.

**To Reproduce**
1. Enter email and password
2. Click on 'Login to Instagram'
3. Check the security code in the email
4. Copy the code
5. Paste in the text input that opens in another view
6. Click on 'Submit code'
4. It doesn't show any error, but it returns to send the code back to the user.

**Expected behavior**

I hope you will enter the application as soon as the security code check is validated.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 16.04

**App version (please complete the following information):**
 - Version 2.8.1

**Comment by andrezap** [comment]
I'm having the same issue but I am receiving the code via phone number.

**Comment by vapstor** [comment]
same here, infinite loop... i'm receiving the code, when i try to put with the space ex: "169 247" a javascript errors occurs, when i try to put "169247" happens the loop

**Comment by ferg13** [comment]
Me, too! So annoying!!! I installed it because Instagram web had limitations, but now are better than this program, so I think I will end to use it. I wasted my time trying to enter in my account.

**Comment by someone857** [comment]
can you all try again with the 3.0.0 version released today and update with the results?

**Comment by ferg13** [comment]
The problem, in my case, starts today, with 3.0.0 version

**Comment by ifedapoolarewaju** [comment]
Do you have 2FA enabled? On your account? 🤔

**Comment by vapstor** [comment]
If you guys don't saw, official Instagram web unlock the messages tool

**Comment by ferg13** [comment]
I receive a security code by email 3 hours later...

**Comment by ifedapoolarewaju** [comment]
> I receive a security code by email 3 hours later...

this is more of an issue from instagram's side. It does come with a delay like this once in a while. However, in the latest release v3.0.0, the 2FA loop has been fixed. I'll close this issue as a result. But if you are still facing this loop, please let me know.

**Comment by ferg13** [comment]
Thank you!
