### ISSUE TITLE
Cannot login using 2FA

### ISSUE THREAD

**Issue by kalarse** [igdmapps/igdm#1268]
I have 2FA enable using Authy, and igdm does not accept the code that Authy app is giving me.
I'd prefer not to disable 2FA in order to login if possible. :(

**Comment by sgroening** [comment]
Exactly the same issue I'm facing. 2FA is recognised in respect to the account itself, but the codes are somehow deemed invalid. This is v. 2.8.1.

**Comment by ifedapoolarewaju** [comment]
this issue is fixed in the latest release v3.0.0
