### ISSUE TITLE
Since last update I can no longer copy/paste text from/to any text box

### ISSUE THREAD

**Issue by joecabezas** [igdmapps/igdm#1296]
**To Reproduce**
 * copy any text from a chat, paste it in an external program, it does not put the selected text in the clipboard
 * paste any text from outside to text field in chat, it does not paste the content of the clipboard 
 
**Expected behavior**
I expect to be able to copy text from chats, or paste text into chat text box to send it but neither works

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.4 Catalina

**App version (please complete the following information):**
 - Version 3.0.0

**Additional context**

**Comment by ifedapoolarewaju** [comment]
this is now fixed in version v3.0.1. Thank you for reporting!
