### ISSUE TITLE
Images don't load for either the user profiles or other areas in the chat

### ISSUE THREAD

**Issue by ElEmFurt** [igdmapps/igdm#1398]
Here's a screenshot, not sure what I am missing, and why the images aren't loading.

![image](https://user-images.githubusercontent.com/73025802/117100484-79c8d480-ad91-11eb-8a00-7ab60a4457f0.png)

**Comment by ElEmFurt** [comment]
Will try the downgrade to 3.0.0 as per comment on a similar issue.

**Comment by bryanyang92** [comment]
i am same after update new version!
