### ISSUE TITLE
error logging attribution

### ISSUE THREAD

**Issue by justgh** [igdmapps/igdm#1422]
Perpetual logging in on 3.0.1
and in 3.0.2 and 3.0.3 it gives an error "error logging attribution"
I use a Mac

 Seems to be an issue with the server just not connecting to insta. Anyone having the same issue?

**Comment by rupalm24** [comment]
Same mistake for Windows

**Comment by Anzio1000** [comment]
Also cannot login to igdm. Using Windows 10. 

IGDM is a defective program.

**Comment by justgh** [comment]
Issue has been fixed. Thank you!
