### ISSUE TITLE
IG dm not working

### ISSUE THREAD

**Issue by Goxi24** [igdmapps/igdm#1458]
I have issues with the IG dm app. 4 days stays in this condition. Tried everything, nothing works. 
Give me advise how to repair this or fix it please from your side.
![IGdm](https://user-images.githubusercontent.com/97060760/147976012-5f926df2-1d31-4359-9486-52e054a6c14a.jpg)

**Comment by PhillipmLavrador** [comment]
When I first opened it, it worked fine. 2 hours later I opened it again it wouldnt work no matter what I did. Did you find a fix?

**Comment by Goxi24** [comment]
Nope...7 days and counting.
