### ISSUE TITLE
Can not Login - GET /api/v1/fbsearch/suggested_searches/?type=blended - 404 Not Found;

### ISSUE THREAD

**Issue by mbahkemo** [igdmapps/igdm#1466]
Cannot login with message :
GET /api/v1/fbsearch/suggested_searches/?type=blended - 404 Not Found;
What's wrong with it ? Please solve

**Comment by bentleycodes** [comment]
Having the same issue here! I have tried clearing apps and websites settings on instagram & checking active log in sessions. No luck

**Comment by iPnx36** [comment]
Same issue

**Comment by jmbflat** [comment]
Duplicate thread:  https://github.com/igdmapps/igdm/issues/1467#issue-1140700458

**Comment by khushrawal** [comment]
/api/v1/fbsearch/suggested_searches/?type=blended - 404 Not Found;

same issue
