### ISSUE TITLE
i cant log in to any account and i get this error GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found;

### ISSUE THREAD

**Issue by iPnx36** [igdmapps/igdm#1467]
![image](https://user-images.githubusercontent.com/69019151/154376141-b23894ea-5fcb-4a74-acdc-e5972a121a6f.png)

**Comment by mbahkemo** [comment]
I don't see any response from developer ?

**Comment by iPnx36** [comment]
yeah nothing 
i tried with 4 of my friends and they all have the same issue

**Comment by jmbflat** [comment]
As a temporary workaround, since I'm building and running locally, I went into 
/IGDM/node_modules/instagram-private-api/dist/services/simulate.service.js 

and commented out the following lines to get it working:

//            () => this.client.fbsearch.suggestedSearches('users'),
//            () => this.client.fbsearch.suggestedSearches('blended'),

**Comment by iPnx36** [comment]
didnt find /IGDM/node_modules/instagram-private-api/dist/services/simulate.service.js
do you have discord or any app i can contact you with plz ?

**Comment by inbomber** [comment]
same issue here, any update?

**Comment by iPnx36** [comment]
nop

**Comment by mbahkemo** [comment]
keep monitor....still no update

**Comment by jmbflat** [comment]
Problem is an update to instagram's api.  The local fix is to bump the version in package.js when building from:

"instagram-private-api": "^1.44.1",

to

"instagram-private-api": "^1.45.3"

while this works for me locally, it may break other things, so a project dev will have to manage the right way to do this.  If you are cloning the git project and running npm install and npm start, I can confirm this fixes the issue.  Could well break something else, so use at your own risk until a dev pushes an update

**Comment by iPnx36** [comment]
i can login in, but its show's nothing

**Comment by mbahkemo** [comment]
![image](https://user-images.githubusercontent.com/86633802/154980607-f1652795-fb6c-4d7b-a1f6-597e27c3f550.png)

Remain the same

**Comment by hugohamelcom** [comment]
Same here

**Comment by mbahkemo** [comment]
Any development there ?

**Comment by iPnx36** [comment]
any update ?

**Comment by Wulfen123** [comment]
This error is annoying af anyone got a fix for this?

**Comment by opdafd2** [comment]
What can I do if I don't have node_modules in my IGdm folder? I tried changing the version in app.asar from 1.44.1 to 1.45.3  and IGdm just doesn't open anymore afterwards

this is how my folders look like
![a5ca54e33c6043de769633eb125df747](https://user-images.githubusercontent.com/100243682/160940009-dcb335b7-c244-4e7c-a137-d83dcc7f51ed.png)

![c5fd149d7de753527215b1ed177425f0](https://user-images.githubusercontent.com/100243682/160940281-49b8a03d-9391-47e8-b815-769b32b3c41e.png)

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed. Please download the latest version on igdm.me
