### ISSUE TITLE
igDM can't login... an error appears

### ISSUE THREAD

**Issue by davidnewcombcl** [igdmapps/igdm#1471]
I can't connect or login to instagram igDM pro (paid app) in my macbook
and I installed igDM to a PC computer and it didn't work either... 
It appears an error when I log in:
GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found;
What is going on?
Thanks in advance.
David Newcomb

**Comment by mbahkemo** [comment]
same with issue #1467 #1468
