### ISSUE TITLE
My loggin info is totall correct,still i can't log in. It says "GET /api/v1/fbsearch/suggested_searches/?type=blended - 404 Not Found;"

### ISSUE THREAD

**Issue by j0kerwav** [igdmapps/igdm#1480]

**Comment by thee038** [comment]
Hello, 

Does it mean that there is no sollution to this loin error?

Please direct me well enough.

**Comment by Wulfen123** [comment]
> Hello,
> 
> Does it mean that there is no sollution to this loin error?
> 
> Please direct me well enough.

No solution getting the same issues as well unable to login, enter login details and password and then the error shows below login screen

**Comment by j0kerwav** [comment]
> Hello,
> 
> Does it mean that there is no sollution to this loin error?
> 
> Please direct me well enough.

Still no solution,but something strange happened. The password from my last account was "jtpko2578",and since i tried logging in with IGDM my account was kinda hacked,when i tried to login from my phone with official instagram app from play store,it said "please confirm that this is your account by typing in the code we sent to j*******8". The problem is,i never had an email like that,i never even used an email in my life that starts with "j" and ends with "8". When i looked at it a little bit better,the email they are talking about is looking pretty much like my PASSWORD ( Jtpko2578). It looks like some bug or glitch in instagram happened and made an unexisting email or email that isnt mine from my password. So they missunderstood my password and made it into an email "jtpko2578@gmail.com"..... WHAT      THE    F**K????????

**Comment by yelafingaz** [comment]
> > Hello,
> > Does it mean that there is no sollution to this loin error?
> > Please direct me well enough.
> 
> Still no solution,but something strange happened. The password from my last account was "jtpko2578",and since i tried logging in with IGDM my account was kinda hacked,when i tried to login from my phone with official instagram app from play store,it said "please confirm that this is your account by typing in the code we sent to j*******8". The problem is,i never had an email like that,i never even used an email in my life that starts with "j" and ends with "8". When i looked at it a little bit better,the email they are talking about is looking pretty much like my PASSWORD "jtpko2578" (starts with "j" and ends with "8"). It looks like some bug or glitch in instagram happened and made an unexisting email or email that isnt mine from my password. So they missunderstood my password and made it into an email "[jtpko2578@gmail.com](mailto:jtpko2578@gmail.com)"..... WHAT THE F**K????????

Nah you just accidentally typed your password into the user field and didn't notice.

**Comment by yelafingaz** [comment]
Would be nice if the developer watched the github for their own fucking application and made any sort of attempt what-so-ever to reply to bugs. Fvckloads of people are having this problem and they cant even update us to let us know that they have other shite to worry about for the time being or something.

FWIW my tablet with Windows 8 is still running the app strong. So, it's not a dependency problem. It's an issue with the actual new(er) application build itself.
