### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Wulfen123** [igdmapps/igdm#1482]
POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found;

**Comment by Wulfen123** [comment]
GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found;

Now the error changed to this

**Comment by mbahkemo** [comment]
Since a month ago

**Comment by Wulfen123** [comment]
> Since a month ago

Was working fine a couple days ago for me till i tried opening it yesterday

**Comment by mbahkemo** [comment]
not sure, i post this issue last month and still same

**Comment by mbahkemo** [comment]
don't now it will be fixed or not :-(
