### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by TheBlinded** [igdmapps/igdm#982]
Is it planned to support this feature? I always get this error, update after update:

> You have two factor authentication enabled. Two factor authentication is not yet supported.

_In any case, thank you for your work, very precious!_

**Comment by TheBlinded** [comment]
Unfortunately this don't resolve "my" problem... thanks anyway!

**Comment by belaarany** [comment]
Still waiting for this feature!

**Comment by ifedapoolarewaju** [comment]
[2FA is now supported](https://github.com/igdmapps/igdm/releases/tag/v2.8.0), so this should no longer be an issue
